from abc import abstractmethod
import ctypes
import fcntl
import logging
import selectors
import signal
import time
from typing import Any, SupportsFloat
import uuid
import gymnasium as gym
import os
import glob
import csv
import io
from posix_ipc import Semaphore, O_CREAT, BusyError
from .action_controller import ActionController
from .datalake import SQLiteDatabaseAPI
from importlib.machinery import SourceFileLoader
import types
import subprocess
from time import perf_counter


LOGGER = logging.getLogger("nsoran.ns_env")


def _set_parent_death_signal():
    """Linux-only: make the child receive SIGTERM if the Python parent dies abruptly."""
    try:
        libc = ctypes.CDLL(None)
        pr_set_pdeathsig = 1
        libc.prctl(pr_set_pdeathsig, signal.SIGTERM)
    except Exception:
        # Best effort only; normal shutdown still goes through close().
        pass


def _format_reproduction_command(script_executable, parameters, debug=False):
    command = [script_executable] + [f"--{param}={value}" for param, value in parameters.items()]
    if debug:
        command = ["gdb", "--args"] + command
    return " ".join(command)


def _safe_get_sem_commands(scenario, sim_result, script_executable):
    try:
        import sem  # type: ignore

        complete_command = sem.utils.get_command_from_result(scenario, sim_result)
        complete_command_debug = sem.utils.get_command_from_result(
            scenario, sim_result, debug=True
        )
    except Exception:
        parameters = sim_result.get("params", {})
        complete_command = _format_reproduction_command(
            script_executable, parameters, debug=False
        )
        complete_command_debug = _format_reproduction_command(
            script_executable, parameters, debug=True
        )
    return complete_command, complete_command_debug


class NsOranEnv(gym.Env):
    """Base abstract class for a ns-O-RAN enviroment compliant with Gymnasium"""
    metadata = {'render_modes': ['ansi']}
    ns3_path: str
    scenario : str  
    scenario_configuration: dict
    output_folder: str
    optimized : bool
    skip_configuration : bool
    sim_path : str
    sim_process : subprocess.Popen
    metricsReadySemaphore : Semaphore
    controlSemaphore : Semaphore
    control_header : list
    log_file: str
    control_file: str
    is_open: bool
    action_controller: ActionController
    datalake: SQLiteDatabaseAPI

    def __init__(self, render_mode:str=None, ns3_path:str=None, scenario:str=None, scenario_configuration:dict=None, output_folder:str=None,
                 optimized:bool=True, skip_configuration:bool=False, control_header: list = [], log_file: str = '', control_file: str = ''):
        """Initialize environment 
        Args:
            render_mode (str): Select one of the render modes available.
            ns3_path (str): Path to the ns-3 folder.
            scenario (str): Name of the simulation scenario to be executed.
            scenario_configuration (dict): Dictionary containing the attributes of the simulation scenario.
            output_folder (str): Output folder for the simulation data.
            optimized (bool): If set, the environment will run ns-3 in an optimized mode.
            skip_configuration (bool): If set, the environment will skip the configuration phase.
            control_header (list): list of features that composes the control action specific to the use case.
            log_file (str): name of the file that saves the action generated by the agent in the simulation output folder.
            control_file (str): name of the file that delivers the action generated by the agent to the simulation.
        """

        if render_mode and render_mode not in self.metadata['render_modes']:
            raise ValueError(f'{render_mode} is not a valid render mode. Values accepted are: {self.metadata["render_modes"]}')
        self.render_mode = render_mode

        self.ns3_path = ns3_path
        self.scenario = scenario            
        self.scenario_configuration = {k: v[0] for k, v in scenario_configuration.items() if v}
        self.output_folder = output_folder
        self.optimized = optimized
        self.skip_configuration = skip_configuration
        self.control_header = control_header
        self.log_file = log_file
        self.control_file = control_file

        self.is_open = False
        self.return_info = False
        self._csv_read_state = {}
        self._reset_count = 0
        self._step_count = 0

        self.setup_sim()
    
    def setup_sim(self):
        """Setup all the relevant parameters to configure, compile and execute the simulation.
           This should be called once and it is mostly taken from sem.runner.SimulationRunner::__init__().
        """
        if self.optimized:
            # For old ns-3 installations, the library is in build, while for
            # recent ns-3 installations it's in build/lib. Both paths are
            # thus required to support all versions of ns-3.
            library_path = "%s:%s" % (
                os.path.join(self.ns3_path, 'build/optimized'),
                os.path.join(self.ns3_path, 'build/optimized/lib'))
        else:
            library_path = "%s:%s" % (
                os.path.join(self.ns3_path, 'build/'),
                os.path.join(self.ns3_path, 'build/lib'))
        
        # We use both LD_ and DYLD_ to support Linux and Mac OS.
        self.environment = {
            'LD_LIBRARY_PATH': library_path,
            'DYLD_LIBRARY_PATH': library_path}
        
        # Configure and build ns-3
        self.configure_and_build_ns3()

        # ns-3's build status output is used to get the executable path for the
        # specified script.
        if os.path.exists(os.path.join(self.ns3_path, "ns3")):
            # In newer versions of ns-3 (3.36+), the name of the build status file is 
            # platform-dependent
            build_status_fname = ".lock-ns3_%s_build" % os.sys.platform
            build_status_path = os.path.join(self.ns3_path, build_status_fname)
        else:
            build_status_fname = "build.py"
            if self.optimized:
                build_status_path = os.path.join(self.ns3_path,
                                                'build/optimized/build-status.py')
            else:
                build_status_path = os.path.join(self.ns3_path,
                                                'build/build-status.py')

        # By importing the file, we can naturally get the dictionary
        loader = SourceFileLoader(build_status_fname, build_status_path)
        mod = types.ModuleType(loader.name)
        loader.exec_module(mod)
        
        # Search is simple: we look for the script name in the program field.
        # Note that this could yield multiple matches, in case the script name
        # string is contained in another script's name.
        # matches contains [program, path] for each program matching the script
        matches = [{'name': program,
                    'path': os.path.abspath(os.path.join(self.ns3_path, program))} for
                   program in mod.ns3_runnable_programs if self.scenario
                   in program]

        if not matches:
            raise ValueError(f"Cannot find {self.scenario} script")

        # To handle multiple matches, we take the 'better matching' option,
        # i.e., the one with length closest to the original script name.
        match_percentages = map(lambda x: {'name': x['name'],
                                           'path': x['path'],
                                           'percentage':
                                           len(self.scenario)/len(x['name'])},
                                matches)

        self.script_executable = max(match_percentages, key=lambda x: x['percentage'])['path']

        # This step is not needed for CMake versions of ns-3
        if "scratch" in self.script_executable and not os.path.exists(os.path.join(self.ns3_path, "ns3")):
            path_with_subdir = self.script_executable.split("/scratch/")[-1]
            if "/" in path_with_subdir:  # Script is in a subdir
                executable_subpath = "%s/%s" % (self.scenario, self.scenario)
            else:  # Script is in scratch root
                executable_subpath = self.scenario

            if self.optimized:
                self.script_executable = os.path.abspath(
                    os.path.join(self.ns3_path,
                                 "build/optimized/scratch",
                                 executable_subpath))
            else:
                self.script_executable = os.path.abspath(
                    os.path.join(self.ns3_path,
                                 "build/scratch",
                                 executable_subpath))

    def configure_and_build_ns3(self):
        """
        Configure and build the ns-3 code, the code is taken from sem.runner.SimulationRunner::configure_and_build().
        """  
        build_program = "./ns3" if os.path.exists(os.path.join(self.ns3_path, "ns3")) else "./waf"

        # Only configure if necessary
        if not self.skip_configuration:
            configuration_command = ['python3', build_program, 'configure',
                                     '--enable-examples', '--disable-gtk',
                                     '--disable-werror']

            if self.optimized:
                configuration_command += ['--build-profile=optimized',
                                          '--out=build/optimized']

            # Check whether path points to a valid installation
            self._run_ns3_command(configuration_command)

        # Build ns-3
        # We don't care about the progress bar of the SimulationRunner, thus we use subprocess.run and wait the build to end
        j_argument = ['-j', str(os.cpu_count())] # if this makes problems just cut it
        self._run_ns3_command(['python3', build_program] + j_argument + ['build'])

    def _run_ns3_command(self, command: list[str]):
        result = subprocess.run(
            command,
            cwd=self.ns3_path,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        if result.returncode != 0:
            stdout = (result.stdout or "").strip()
            stderr = (result.stderr or "").strip()
            error_parts = [f"ns-3 command failed ({result.returncode}): {' '.join(command)}"]
            if stdout:
                error_parts.append(f"stdout:\n{stdout}")
            if stderr:
                error_parts.append(f"stderr:\n{stderr}")
            raise RuntimeError("\n\n".join(error_parts))
        return result
        
    def start_sim(self):
        """
            Start the ns-3 simulation and all the entities to manage the control, i.e.,:
                1 - Create simulation folder inside the output folder chosen by the user.
                2 - Create Datalake and Action Controller.
                3 - Create the Semaphores.
                4 - Start the Simulation.
        """
        if self.is_open:
            raise ValueError('The environment is open and a new start_sim has been called.')
   
        self.is_open = True
        self._csv_read_state = {}
        # We may need to explicit the default values as well here, but for the moment we only change the values of the configuration
        # A good way would be to explict such values is to port here sem.manager.CampaignManager::check_and_fill_parameters
        parameters = self.scenario_configuration
        
        # sem.CampaignManager.check_and_fill_parameters()

        ### Create simulation folder inside the output folder chosen by the user, mostly taken from sem.runner.SimulationRunner::run_simulations() ###
        self.sim_result = { 'params': {}, 'meta': {} }
        self.sim_result['params'].update(parameters)

        n_core = 1
        command = [self.script_executable]
        if n_core > 1:
            command = ['mpirun', '-np', str(n_core)] + command
        command.extend(f'--{param}={value}' for param, value in parameters.items())
        
        # Run from dedicated self.sim_path folder
        sim_uuid = str(uuid.uuid4())
        self.sim_result['meta']['id'] = sim_uuid
        self.sim_path = os.path.join(self.output_folder, self.sim_result['meta']['id'])
        os.makedirs(self.sim_path)

        ### End create simulation folder ###

        ### Create Datalake and Action Controller ###

        if not self.log_file:
            raise ValueError('Missing the log file path.')

        if not self.control_file:
            raise ValueError('Missing the control file path.')

        if not self.control_header:
            raise ValueError('Missing the list of values to perform control.')

        self.action_controller = ActionController(self.sim_path, self.log_file, self.control_file, self.control_header)
        self.datalake = SQLiteDatabaseAPI(
            self.sim_path,
            num_ues=self.sim_result['params'].get('ues'),
            debug=False,
        )
        
        self._init_datalake_usecase()

        ### End Datalake and Action Controller ###

        ### Create the Semaphores ###

        nameMetricsReadySemaphore = "/sem_metrics_" + self.sim_path.split('/')[-1]
        nameControlSemaphore = "/sem_control_" + self.sim_path.split('/')[-1]
        self.metricsReadySemaphore = Semaphore(nameMetricsReadySemaphore, O_CREAT, mode=0o660, initial_value=0)
        self.controlSemaphore = Semaphore(nameControlSemaphore, O_CREAT, mode=0o660, initial_value=0)
        self.last_timestamp = 0
        self.last_source_timestamp = 0
        self._current_batch_timestamp = 0
        
        ### End create the Semaphores ###
        
        ### Launch simulation ###
       
        # launch the simulation with the wanted configuration
        # Store process id or whatever reference we can use for the simulation
        
        self.sim_result['meta']['start_time'] = time.time()
        LOGGER.info(
            "Starting ns-3 simulation | scenario=%s sim_path=%s command=%s",
            self.scenario,
            self.sim_path,
            " ".join(command),
        )
        LOGGER.info(
            "Semaphore names | metrics=%s control=%s",
            nameMetricsReadySemaphore,
            nameControlSemaphore,
        )
        
        self.sim_process = subprocess.Popen(
            command,
            cwd=self.sim_path,
            env=self.environment,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            preexec_fn=_set_parent_death_signal if os.name == "posix" else None,
        )

        # Register the stdout and stderr file descriptors with the selector
        self.selector = selectors.DefaultSelector()

        # Set non-blocking mode for stdout and stderr
        self._set_nonblocking(self.sim_process.stdout)
        self._set_nonblocking(self.sim_process.stderr)

        self.selector.register(self.sim_process.stdout, selectors.EVENT_READ)
        self.selector.register(self.sim_process.stderr, selectors.EVENT_READ)
        ### End create simulation ###
        self._log_resource_snapshot("start_sim")

    @staticmethod
    def _get_open_fd_count() -> int | None:
        try:
            return len(os.listdir(f"/proc/{os.getpid()}/fd"))
        except OSError:
            return None

    @staticmethod
    def _get_rss_kb() -> int | None:
        try:
            with open(f"/proc/{os.getpid()}/status", "r", encoding="utf-8") as status_file:
                for line in status_file:
                    if line.startswith("VmRSS:"):
                        parts = line.split()
                        if len(parts) >= 2:
                            return int(parts[1])
                        break
        except OSError:
            return None
        return None

    def _log_resource_snapshot(self, event: str):
        output_dir_count = None
        if self.output_folder and os.path.isdir(self.output_folder):
            try:
                output_dir_count = len(
                    [
                        entry
                        for entry in os.scandir(self.output_folder)
                        if entry.is_dir()
                    ]
                )
            except OSError:
                output_dir_count = None

        LOGGER.info(
            "Resource snapshot | event=%s scenario=%s sim_path=%s reset_count=%s step_count=%s rss_kb=%s open_fd_count=%s csv_state_entries=%s output_dir_count=%s process_alive=%s",
            event,
            self.scenario,
            getattr(self, "sim_path", None),
            self._reset_count,
            self._step_count,
            self._get_rss_kb(),
            self._get_open_fd_count(),
            len(self._csv_read_state),
            output_dir_count,
            getattr(getattr(self, "sim_process", None), "poll", lambda: None)() is None if getattr(self, "sim_process", None) else False,
        )

    @staticmethod
    def _set_nonblocking(fileobj):
        """Function to set non-blocking mode a fileobject. This ensures that the select() and read() of I/O are not blocking
        """
        fd = fileobj.fileno()
        flags = fcntl.fcntl(fd, fcntl.F_GETFL)
        fcntl.fcntl(fd, fcntl.F_SETFL, flags | os.O_NONBLOCK)
        
    def read_streams(self):
        events = self.selector.select(timeout=0)  # Non-blocking check
        
        stdout_file_path = os.path.join(self.sim_path, 'stdout')
        stderr_file_path = os.path.join(self.sim_path, 'stderr')
        
        with open(stdout_file_path, 'a+') as stdout_file, open(
                stderr_file_path, 'a+') as stderr_file:
            for key, _ in events:
                data = key.fileobj.read()
                if not data:
                    continue               
                if key.fileobj is self.sim_process.stdout:
                    stdout_file.write(data)
                elif key.fileobj is self.sim_process.stderr:
                    stderr_file.write(data)
    
    def is_simulation_over(self) -> bool:
        """Checks whether the simulation is over or not.
        """
        self.read_streams()
        if self.sim_process.poll() is None:
            return False

        # Ensure any remaining output is processed
        self.read_streams()

        end = time.time() 
        return_code = self.sim_process.returncode

        if return_code != 0:
            # The environment should return truncated.
            self.terminated = False
            self.truncated = True

            stdout_file_path = os.path.join(self.sim_path, 'stdout')
            stderr_file_path = os.path.join(self.sim_path, 'stderr')

            with open(stdout_file_path, 'r') as stdout_file, open(
                        stderr_file_path, 'r') as stderr_file:
                complete_command, complete_command_debug = _safe_get_sem_commands(
                    self.scenario, self.sim_result, self.script_executable
                )
                error_message = (f'\nSimulation exited with an error.\nStderr: {stderr_file.read()}\n'
                                    f'Stdout: {stdout_file.read()}\nUse this command to reproduce:\n{complete_command}\n'
                                    f'Debug with gdb:\n{complete_command_debug}')
                
                print(error_message) 
        else:
            # The environment should return terminated and truncated since it is a time limit imposed
            self.terminated = True
            self.truncated = True

        self.sim_result['meta']['elapsed_time'] = end - self.sim_result['meta']['start_time'] 
        self.sim_result['meta']['exitcode'] = return_code
        
        return True

    def reset(self, *, seed: int | None = None, options: dict[str, Any] | None = None):
        reset_started_at = perf_counter()
        #print("calling super reset")
        super().reset(seed=seed)
        #print("super reset done, closing")
        self.close()
        self._reset_count += 1
        #print("about to start sim")
        self.start_sim()
        #print("sim started")
        if options:
            if 'return_info' in options:
                self.return_info = options['return_info']
            else:
                self.return_info = False
        else:
            # Set here all the default settings
            self.return_info = False
        defer_initial_observation = bool((options or {}).get("defer_initial_observation", False))

        if defer_initial_observation:
            self.terminated = False
            self.truncated = False
            self._deferred_initial_observation_pending = True
            self._await_first_kpi_after_deferred_reset = True
            LOGGER.info(
                "Reset deferred initial observation | scenario=%s sim_path=%s total_reset_s=%.3f",
                self.scenario,
                self.sim_path,
                perf_counter() - reset_started_at,
            )
            self._log_resource_snapshot("reset_deferred")
            empty_obs_frame = None
            if hasattr(self, "_build_empty_observations_frame"):
                try:
                    empty_obs_frame = self._build_empty_observations_frame()
                except Exception:
                    empty_obs_frame = None
            if empty_obs_frame is not None and hasattr(empty_obs_frame, "iloc"):
                obs = [tuple(empty_obs_frame.iloc[0].values)]
            else:
                obs = []
            return (obs, self.render()) if self.return_info else (obs, {})

        # The simulation may signal metrics readiness before the first KPI files
        # are fully populated. Keep waiting until at least one timestamp is ingested.
        initial_reset_timeout = getattr(self, "initial_reset_timeout_seconds", 120)
        poll_timeout = getattr(self, "initial_reset_poll_timeout_seconds", 5)
        deadline = time.time() + initial_reset_timeout
        wait_attempt = 0
        while time.time() < deadline:
            wait_attempt += 1
            remaining_seconds = max(1, int(deadline - time.time()))
            current_poll_timeout = min(poll_timeout, remaining_seconds)
            wait_started_at = perf_counter()
            self._wait_data_availability(timeout=current_poll_timeout)
            wait_elapsed = perf_counter() - wait_started_at
            fill_started_at = perf_counter()
            self._fill_datalake()
            fill_elapsed = perf_counter() - fill_started_at
            if self.last_timestamp > 0:
                LOGGER.info(
                    "Initial KPI data available | scenario=%s sim_path=%s wait_attempt=%s last_timestamp=%s wait_s=%.3f fill_s=%.3f total_reset_s=%.3f",
                    self.scenario,
                    self.sim_path,
                    wait_attempt,
                    self.last_timestamp,
                    wait_elapsed,
                    fill_elapsed,
                    perf_counter() - reset_started_at,
                )
                break
            LOGGER.warning(
                "Initial metrics arrived before KPI rows were populated | scenario=%s sim_path=%s wait_attempt=%s last_timestamp=%s remaining_reset_timeout=%ss wait_s=%.3f fill_s=%.3f",
                self.scenario,
                self.sim_path,
                wait_attempt,
                self.last_timestamp,
                max(0, int(deadline - time.time())),
                wait_elapsed,
                fill_elapsed,
            )
            # During reset, ns-3 may already be blocked in ReadControlFile() waiting
            # for the control semaphore after posting the first "metrics ready"
            # signal. Release it so the simulation can advance to the next KPI batch.
            try:
                self.controlSemaphore.release()
                LOGGER.info(
                    "Released controlSemaphore during reset warm-up | scenario=%s sim_path=%s wait_attempt=%s",
                    self.scenario,
                    self.sim_path,
                    wait_attempt,
                )
            except Exception as exc:
                LOGGER.warning(
                    "Unable to release controlSemaphore during reset warm-up | scenario=%s sim_path=%s wait_attempt=%s error=%s",
                    self.scenario,
                    self.sim_path,
                    wait_attempt,
                    exc,
                )
        else:
            LOGGER.error(
                "No KPI rows were populated before initial reset timeout | scenario=%s sim_path=%s last_timestamp=%s initial_reset_timeout=%s poll_timeout=%s wait_attempts=%s",
                self.scenario,
                self.sim_path,
                self.last_timestamp,
                initial_reset_timeout,
                poll_timeout,
                wait_attempt,
            )
        
        self.terminated = False
        self.truncated = False

        # The Action is computed in the step, thus the control semaphore is not released
        obs_started_at = perf_counter()
        obs = self._get_obs()
        obs_elapsed = perf_counter() - obs_started_at
        LOGGER.info(
            "Reset completed | scenario=%s sim_path=%s last_timestamp=%s total_reset_s=%.3f get_obs_s=%.3f",
            self.scenario,
            self.sim_path,
            self.last_timestamp,
            perf_counter() - reset_started_at,
            obs_elapsed,
        )
        self._log_resource_snapshot("reset_completed")
        return (obs, self.render()) if self.return_info else (obs, {})

    def _wait_data_availability(self, timeout: int = 10):
        # Wait for the new metrics to be available
        is_still_active = True
        attempts = 0
        while is_still_active:
            try:
                self.metricsReadySemaphore.acquire(timeout=timeout)
                LOGGER.info(
                    "metricsReadySemaphore acquired | scenario=%s sim_path=%s attempts=%s last_timestamp=%s",
                    self.scenario,
                    self.sim_path,
                    attempts,
                    self.last_timestamp,
                )
                break
            except BusyError: # The timeout has elapsed, so we need to check again whether the simulation is over or not
                attempts += 1
                LOGGER.warning(
                    "metricsReadySemaphore timeout | scenario=%s sim_path=%s attempts=%s timeout=%ss last_timestamp=%s process_alive=%s",
                    self.scenario,
                    self.sim_path,
                    attempts,
                    timeout,
                    self.last_timestamp,
                    self.sim_process.poll() is None,
                )
                is_still_active = not self.is_simulation_over()

    def _drain_metrics_ready_notifications(self):
        drained = 0
        while True:
            try:
                self.metricsReadySemaphore.acquire(timeout=0)
                drained += 1
            except BusyError:
                break
        if drained:
            LOGGER.info(
                "Drained stale metricsReady notifications | scenario=%s sim_path=%s count=%s last_timestamp=%s",
                self.scenario,
                self.sim_path,
                drained,
                self.last_timestamp,
            )
        return drained

    def step(self, action: object) -> tuple[object, SupportsFloat, bool, bool, dict[str, Any]]:
        step_started_at = perf_counter()
        self._step_count += 1
        #print("calling step")
        # Simulation is open in Gym, but it can be terminated in ns-3
        if not self.is_simulation_over():
            # Take a step in the environment based on the given action
            action_started_at = perf_counter()
            actions = self._compute_action(action)
            compute_action_elapsed = perf_counter() - action_started_at

            if getattr(self, "_deferred_initial_observation_pending", False):
                self._drain_metrics_ready_notifications()
                self._deferred_initial_observation_pending = False
            
            # Update the environment state and calculate the reward
            control_started_at = perf_counter()
            self.action_controller.create_control_action(self.last_timestamp, actions)
            # the action was written: notify the environment
            self.controlSemaphore.release()
            control_elapsed = perf_counter() - control_started_at
            
            wait_started_at = perf_counter()
            self._wait_data_availability()            
            wait_elapsed = perf_counter() - wait_started_at
            fill_started_at = perf_counter()
            self._fill_datalake()
            fill_elapsed = perf_counter() - fill_started_at
            while getattr(self, "_await_first_kpi_after_deferred_reset", False) and self.last_timestamp <= 0 and not self.is_simulation_over():
                LOGGER.info(
                    "Discarding bootstrap KPI batch after deferred reset | scenario=%s sim_path=%s last_timestamp=%s",
                    self.scenario,
                    self.sim_path,
                    self.last_timestamp,
                )
                control_started_at = perf_counter()
                self.action_controller.create_control_action(self.last_timestamp, actions)
                self.controlSemaphore.release()
                control_elapsed += perf_counter() - control_started_at
                wait_started_at = perf_counter()
                self._wait_data_availability()
                wait_elapsed += perf_counter() - wait_started_at
                fill_started_at = perf_counter()
                self._fill_datalake()
                fill_elapsed += perf_counter() - fill_started_at
            if getattr(self, "_await_first_kpi_after_deferred_reset", False) and self.last_timestamp > 0:
                self._await_first_kpi_after_deferred_reset = False
        else:
            compute_action_elapsed = 0.0
            control_elapsed = 0.0
            wait_elapsed = 0.0
            fill_elapsed = 0.0
        
        obs_started_at = perf_counter()
        obs = self._get_obs()
        obs_elapsed = perf_counter() - obs_started_at
        reward_started_at = perf_counter()
        reward = self._compute_reward()
        reward_elapsed = perf_counter() - reward_started_at

        if self.return_info:
            return_tuple = (obs, reward, self.terminated, self.truncated, self.render()) 
        else:
            return_tuple = (obs, reward, self.terminated, self.truncated, {})

        LOGGER.info(
            "Step timing | scenario=%s sim_path=%s last_timestamp=%s compute_action_s=%.3f control_s=%.3f wait_s=%.3f fill_s=%.3f get_obs_s=%.3f reward_s=%.3f total_step_s=%.3f",
            self.scenario,
            self.sim_path,
            self.last_timestamp,
            compute_action_elapsed,
            control_elapsed,
            wait_elapsed,
            fill_elapsed,
            obs_elapsed,
            reward_elapsed,
            perf_counter() - step_started_at,
        )
        if self._step_count % 25 == 0:
            self._log_resource_snapshot("step_periodic")

        return return_tuple
    
    def _fill_datalake(self):
        """Helper function that collects from the csv files the latest kpms and uploads them in the Datalake
        """
        fill_started_at = perf_counter()
        self.datalake.acquire_connection()
        previous_timestamp = self.last_timestamp
        pending_rows = []

        for file_path in glob.glob(os.path.join(self.sim_path, 'cu-up-cell-*.txt')):
            cellId = self.datalake.extract_cellId(file_path)
            for row in self._iter_new_csv_rows(file_path):
                pending_rows.append(("cu_up", cellId, int(row["timestamp"]), row))

        for file_path in glob.glob(os.path.join(self.sim_path, 'cu-cp-cell-*.txt')):
            cellId = self.datalake.extract_cellId(file_path)
            for row in self._iter_new_csv_rows(file_path):
                pending_rows.append(("cu_cp", cellId, int(row["timestamp"]), row))

        for file_path in glob.glob(os.path.join(self.sim_path, 'du-cell-*.txt')):
            for row in self._iter_new_csv_rows(file_path):
                pending_rows.append(("du", None, int(row["timestamp"]), row))

        cu_up_rows = sum(1 for table_name, *_ in pending_rows if table_name == "cu_up")
        cu_cp_rows = sum(1 for table_name, *_ in pending_rows if table_name == "cu_cp")
        du_rows = sum(1 for table_name, *_ in pending_rows if table_name == "du")

        if pending_rows:
            source_timestamps = [source_timestamp for _, _, source_timestamp, _ in pending_rows]
            batch_timestamp = max(source_timestamps)
            self._current_batch_timestamp = batch_timestamp
            self.last_source_timestamp = batch_timestamp

            for table_name, cellId, _, raw_row in pending_rows:
                row = dict(raw_row)
                row["timestamp"] = batch_timestamp
                if cellId is not None:
                    row["cellId"] = cellId
                if table_name == "cu_up":
                    if cellId == 1:
                        self.datalake.insert_lte_cu_up(row)
                    else:
                        self.datalake.insert_gnb_cu_up(row)
                elif table_name == "cu_cp":
                    if cellId == 1:
                        self.datalake.insert_lte_cu_cp(row)
                    else:
                        self.datalake.insert_gnb_cu_cp(row)
                else:
                    self.datalake.insert_du(row)

            self.last_timestamp = batch_timestamp

        self._fill_datalake_usecase()
        
        self.datalake.release_connection()
        LOGGER.debug(
            "Fill datalake timing | scenario=%s sim_path=%s prev_timestamp=%s last_timestamp=%s cu_up_rows=%s cu_cp_rows=%s du_rows=%s source_ts_min=%s source_ts_max=%s source_ts_spread_ms=%s elapsed_s=%.3f",
            self.scenario,
            self.sim_path,
            previous_timestamp,
            self.last_timestamp,
            cu_up_rows,
            cu_cp_rows,
            du_rows,
            min(source_timestamps) if pending_rows else None,
            max(source_timestamps) if pending_rows else None,
            (max(source_timestamps) - min(source_timestamps)) if pending_rows else None,
            perf_counter() - fill_started_at,
        )

    def _iter_new_csv_rows(self, file_path: str, delimiter: str = ","):
        state = self._csv_read_state.setdefault(
            file_path,
            {
                "offset": 0,
                "partial": "",
                "fieldnames": None,
                "delimiter": delimiter,
            },
        )
        if state["delimiter"] != delimiter:
            state = {
                "offset": 0,
                "partial": "",
                "fieldnames": None,
                "delimiter": delimiter,
            }
            self._csv_read_state[file_path] = state

        try:
            file_size = os.path.getsize(file_path)
        except OSError:
            return []

        if state["offset"] > file_size:
            state["offset"] = 0
            state["partial"] = ""
            state["fieldnames"] = None

        with open(file_path, "r", encoding="utf-8", newline="") as csvfile:
            csvfile.seek(state["offset"])
            chunk = csvfile.read()
            state["offset"] = csvfile.tell()

        if not chunk and not state["partial"]:
            return []

        text = state["partial"] + chunk
        if not text:
            return []

        if text.endswith("\n") or text.endswith("\r"):
            complete_text = text
            state["partial"] = ""
        else:
            lines = text.splitlines(keepends=True)
            if len(lines) == 1:
                state["partial"] = text
                return []
            complete_text = "".join(lines[:-1])
            state["partial"] = lines[-1]

        lines = complete_text.splitlines()
        if not lines:
            return []

        if state["fieldnames"] is None:
            header_reader = csv.reader([lines[0]], delimiter=delimiter)
            state["fieldnames"] = next(header_reader, None)
            lines = lines[1:]

        if not lines or not state["fieldnames"]:
            return []

        reader = csv.DictReader(
            io.StringIO("\n".join(lines)),
            fieldnames=state["fieldnames"],
            delimiter=delimiter,
        )
        return [row for row in reader if row and any(value not in (None, "") for value in row.values())]

    @abstractmethod
    def _compute_action(self, action) -> list[tuple]:
        """Helper function that converts the agents action defined in Gym into the ns-O-RAN required format according to the use case"""
        raise NotImplementedError('_compute_action() must be implemented for the specific use case')

    @abstractmethod
    def _get_obs(self) -> list:
        """Helper function that returns the curret observation according to the use case"""
        raise NotImplementedError('_get_obs() must be implemented for the specific use case')
    
    @abstractmethod
    def _compute_reward(self):
        """Helper function that returns the curret reward function according to the use case"""
        raise NotImplementedError('_compute_reward() must be implemented for the specific use case')

    @abstractmethod
    def _init_datalake_usecase(self):
        """Function to be implemented by children classes to initialize the additional datalake 
            This function is optional, thus it does not raise an exception.
        """
        pass
    
    @abstractmethod
    def _fill_datalake_usecase(self):
        """Function to be implemented by children to add more data to the datalake
            This function is optional, thus it does not raise an exception.
        """
        pass

    def _get_info(self):
        # TODO deliver last timestamp and time elapsed in the simulation
        return {'isopen': self.is_open, 'results': self.sim_result}
    
    def render(self):
        if self.render_mode == "ansi":
            infos = self._get_info()
            print(infos)
            return infos 
   
    def close(self):
        super().close()
        if self.is_open:
            self._log_resource_snapshot("close_started")
            try:
                if getattr(self, "metricsReadySemaphore", None) is not None:
                    try:
                        self.metricsReadySemaphore.release()
                    except Exception:
                        pass
                if getattr(self, "controlSemaphore", None) is not None:
                    try:
                        self.controlSemaphore.release()
                    except Exception:
                        pass

                if getattr(self, "selector", None) is not None:
                    try:
                        for key in list(self.selector.get_map().values()):
                            try:
                                self.selector.unregister(key.fileobj)
                            except Exception:
                                pass
                    finally:
                        try:
                            self.selector.close()
                        except Exception:
                            pass

                if getattr(self, "sim_process", None) is not None:
                    if self.sim_process.poll() is None:
                        self.sim_process.terminate()
                        try:
                            self.sim_process.wait(timeout=5)
                        except subprocess.TimeoutExpired:
                            self.sim_process.kill()
                            self.sim_process.wait(timeout=5)

                    for stream_name in ("stdout", "stderr"):
                        stream = getattr(self.sim_process, stream_name, None)
                        if stream is not None:
                            try:
                                stream.close()
                            except Exception:
                                pass

                if getattr(self, "datalake", None) is not None:
                    try:
                        if getattr(self.datalake, "connection", None) is not None:
                            self.datalake.release_connection()
                    except Exception:
                        pass

                for sem_name in ("controlSemaphore", "metricsReadySemaphore"):
                    sem = getattr(self, sem_name, None)
                    if sem is None:
                        continue
                    try:
                        sem.close()
                    except Exception:
                        pass
                    try:
                        sem.unlink()
                    except Exception:
                        pass
            finally:
                self.selector = None
                self.sim_process = None
                self.controlSemaphore = None
                self.metricsReadySemaphore = None
                self.action_controller = None
                self.datalake = None
                self._csv_read_state = {}
                self.is_open = False
                self._log_resource_snapshot("close_completed")

    def __del__(self):
        if self.is_open:
            self.close()
